apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: sugang-system
type: Opaque
stringData:
  db-user: "root"
  # DB 비밀번호 (실제 값 입력)
  db-password: "songtime"
  # Gemini API 키 (실제 값 입력)
  gemini-api-key: "AIzaSyAuZmuQbeHVArIKKB0V76qgjX3sqLL4UaA"
