apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: sugang-system
spec:
  type: LoadBalancer # localhost:3000 접속용
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 32565
  selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: sugang-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: krpark1108/frontend:v3 # ✅ 수정 완료: Docker Hub 경로 반영
        imagePullPolicy: Always # ✅ K8s가 Docker Hub에서 이미지를 가져오도록 Always로 변경
        ports:
        - containerPort: 3000
        env:
            - name: VITE_API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: FRONTEND_VITE_API_BASE_URL
            - name: VITE_AUTH_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: FRONTEND_VITE_AUTH_BASE_URL
            - name: VITE_AI_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: FRONTEND_VITE_AI_BASE_URL
            - name: VITE_SCHEDULER_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: FRONTEND_VITE_SCHEDULER_BASE_URL