apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: songtime
type: Opaque
stringData:
  DB_PASSWORD: apppassword
  MYSQL_ROOT_PASSWORD: apppassword
  MYSQL_PASSWORD: apppassword
  JWT_SECRET: "jwt1234!"
  GEMINI_API_KEY: "AIzaSyCKMeR-Pz-_0Q_JcledRU-lUBJKu-ooNGs"
  CRON_SECRET: cloudcloud



